# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/"
    assignees:
      - "Pantastisch"
    open-pull-requests-limit: 50
    labels:
      - "npm"
      - "dependencies"
      - "frontend"

  - package-ecosystem: "nuget"
    directory: "/backend/"
    assignees:
      - "Pantastisch"
    open-pull-requests-limit: 50
    labels:
      - ".NET"
      - "dependencies"
      - "backend"

  - package-ecosystem: "npm"
    directory: "/tests/"
    assignees:
      - "Pantastisch"
    open-pull-requests-limit: 50
    labels:
      - "npm"
      - "dependencies"
      - "tests"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "Pantastisch"
    open-pull-requests-limit: 50
    labels:
      - "github-actions"
      - "dependencies"
      - "devops"

  - package-ecosystem: "docker"
    directory: "/"
    assignees:
      - "Pantastisch"
    open-pull-requests-limit: 50
    labels:
      - "docker"
      - "dependencies"
      - "devops"
