version: "3.7"
services: 

  crms_prod:
    #build: .
    image: crohmcrms/crohm_crms:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - db_prod
    environment:
      - DBServer=ops085010.cs.ohmhs.de
      - DBPort=1433
      - DBUser=SA
      - DBPassword=CRohM2020
      - DBName=CRMDB
    restart: unless-stopped  

  db_prod:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: Y
      # LOGIN: sa
      SA_PASSWORD: CRohM2020
      MSSQL_PID: Express
      TZ: Europe/Berlin
    ports:
      - 1433:1433
    volumes: 
      - database_vol:/var/opt/mssql 
    restart: unless-stopped

volumes: 
  database_vol:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: /srv/crohm/database
