version: "3.7"
services:
  crms:
    image: crohmcrms/crohm_crms:${CROHM_IMAGE}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - db
    environment:
      - DBServer=172.28.0.1
      - DBPort=${DB_PORT}
      - DBUser=CRMSAdmin
      - DBPassword=CRohM2020
      - DBName=CRMDB
      - MailAddress=crohm_nuernberg@hotmail.com
      - MailDisplayName=CRMS-Team
      - MailUserName=crohm_nuernberg@hotmail.com
      - MailPassword=crohm2020
      - MailPort=587
      - MailHost=smtp.office365.com
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Crohm2020!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/crohm-selfsigned.pfx
    volumes:
      - ./https:/https/
    restart: unless-stopped
    networks:
      - crms_net
    links:
      - "db"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      # LOGIN: sa
      SA_PASSWORD: CRohM2020
      MSSQL_PID: Express
      TZ: Europe/Berlin
    ports:
      - ${DB_PORT}:1433
    restart: unless-stopped
    networks:
      - crms_net

networks:
  crms_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
