name: Pull Request Builds
on:
  pull_request:

jobs:

  container_security_scan:
    runs-on: ubuntu-latest
    steps:

    - name: Container Security Scan
      uses: azure/container-scan@v0
      with:
        image-name: crohmcrms/crohm_crms
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  dump:
    runs-on: ubuntu-16.04
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  echo_test:
    runs-on: ubuntu-16.04
    steps:

      - name: Test var
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          SHA7: ${{ github.sha }}
        run: |
          echo "$BRANCH_NAME"
          echo "$SHA7"
